name: Whispering
description: leslie's notes on web
meta_description: "leslie's notes on we"

aboutPage: false

markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'http://geekontheway.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: '1T1Jyp55bC'

# Details for the RSS feed generator
url:            'http://geekontheway.github.io'
author:         'leslie'
authorTwitter:  'geekzh'

permalink:       /:year/:month/:day/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
